### ISSUE TITLE
errore di compilazione con il nuovo comando

### ISSUE THREAD

**Issue by Eliaxie** [federicomor/tdemerger#1]
Il compilatore termina in questo errore:
`Package pdfpages Error: Page 2 of "2014-07-04 Soluzione.pdf" does not exist. \addtde{2014-07-04 Soluzione.pdf}`
Commentando i \addtde che danno quell'errore, si rompe di nuovo con questo errore in uno dei documenti successivi
`Package pdfpages Error: Page 2 of "2015-06-29 Soluzione.pdf" does not exist. \addtde{2015-06-29 Soluzione.pdf}`

Con il comando vecchio non ci sono problemi

**Comment by federicomor** [comment]
Sì è che il vecchio comando funzionava su qualsiasi pdf ma lasciava una pagina semi-vuota prima di inserirlo effettivamente, cioè creava una pagina col titolo della sezione e poi solo nella successiva includeva il pdf. Mentre il nuovo comando evita questo fastidio, cioè riesce a mettere insieme nella stessa pagina il titolo della sezione e il pdf, ma si basa sull'ipotesi che il pdf da includere abbia più di due pagine, che mi sembrava abbastanza debole da poter essere sempre soddisfatta (trattandosi di temi d'esame, quindi documenti in genere più corposi di una singola pagina).

Ma comunque ora ho fatto un po' di nuovi test con un nuovo comando che gestisce entrambi i casi. Cioè prima conta le pagine del pdf da aggiungere e poi utilizza il comando opportuno per quel numero di pagine. Quindi ora dovrebbe funzionare sempre.
Infatti il nuovo comando è:
```
%comando definitivo :)
\newcommand{\addtde}[1]{%
	\pdfximage{#1} %prepara il pdf per il conteggio delle pagine
	\ifthenelse{\the\pdflastximagepages > 1 }% caso con più di 1 pagina:
		{\includepdf[pages=1,pagecommand=\section{#1} \thispagestyle{empty}, scale=0.9]{#1}
		\includepdf[pages=2-,pagecommand={\thispagestyle{empty}}]{#1}}% caso con solo una pagina:
		{\includepdf[pages=1,pagecommand=\section{#1} \thispagestyle{empty}, scale=0.9]{#1}}
}
```
